/* ==========================================================================
   Wild Wisdom Global Challenge 2026-27 — "From Coastline to the Seafloor"
   Mock Exam Question Bank
   Chapters:
     1. Marine Diversity and Distribution
     2. Ocean Ecosystems, Habitats and Interdependence
     3. Life Functions Underwater (Anatomy & Life Processes)
     4. Adaptations and Behaviour
     5. Challenges to Ocean Health
     6. Human-Ocean Interactions and Conservation Stewardship
   ========================================================================== */

const QUESTION_BANK = [

// ============================== CHAPTER 1 ==================================
{id:"c1-01", chapter:1, q:"Scientists describe biodiversity at three levels. Which of the following is NOT one of them?", options:["Genetic diversity","Species diversity","Ecosystem diversity","Population density"], correct:3, explain:"The three recognised levels of biodiversity are genetic, species and ecosystem diversity. Population density is a related but separate ecological measurement."},
{id:"c1-02", chapter:1, q:"An ecosystem has 10 species, with individuals spread almost equally among them. Another ecosystem also has 10 species, but 95% of organisms belong to just one species. Both have the same species richness, but differ in:", options:["Species evenness","Genetic diversity","Ecosystem diversity","Endemism"], correct:0, explain:"Species evenness describes how evenly individuals are distributed among species — richness alone (the number of species) doesn't capture this."},
{id:"c1-03", chapter:1, q:"Why do scientists say 'species richness is not the same as biodiversity'?", options:["Because biodiversity also includes genetic and ecosystem-level variation, not just species counts","Because richness only applies to land animals","Because biodiversity ignores species counts entirely","Because richness is always higher in the ocean"], correct:0, explain:"Biodiversity is broader than just counting species — it includes genetic diversity within species and the diversity of ecosystems too."},
{id:"c1-04", chapter:1, q:"Which group of marine organisms includes the vast majority of marine biodiversity, despite being less familiar to most people?", options:["Vertebrates","Invertebrates","Marine mammals","Seabirds"], correct:1, explain:"Although whales, fish and turtles are more familiar, invertebrates (like corals, molluscs, crustaceans and jellyfish) make up most marine biodiversity."},
{id:"c1-05", chapter:1, q:"Sharks and rays belong to which group of fish, distinguished by a skeleton made mainly of cartilage rather than bone?", options:["Osteichthyes (bony fish)","Chondrichthyes (cartilaginous fish)","Cephalopods","Echinoderms"], correct:1, explain:"Chondrichthyes (sharks, rays, skates and chimaeras) have skeletons made of cartilage, which is lighter and more flexible than bone."},
{id:"c1-06", chapter:1, q:"Which statement about whales is correct?", options:["Whales are fish because they live in the ocean","Whales are mammals that breathe air using lungs","Whales extract oxygen from water using gills","Whales are a type of large fish related to sharks"], correct:1, explain:"Whales are marine mammals — they breathe air with lungs, are warm-blooded, and nurse their young with milk, unlike fish which use gills."},
{id:"c1-07", chapter:1, q:"Which of these is an example of a marine reptile?", options:["Dolphin","Sea turtle","Penguin","Tuna"], correct:1, explain:"Sea turtles (along with sea snakes and marine iguanas) are marine reptiles — they breathe air but spend much of their lives in the ocean."},
{id:"c1-08", chapter:1, q:"Corals belong to which animal group, along with jellyfish and sea anemones?", options:["Molluscs","Echinoderms","Cnidarians","Crustaceans"], correct:2, explain:"Corals are cnidarians — animals with specialised stinging cells — the same broad group as jellyfish and sea anemones."},
{id:"c1-09", chapter:1, q:"Octopus and squid, known for their intelligence and rapid colour-changing skin, belong to which group?", options:["Cephalopods (a type of mollusc)","Crustaceans","Echinoderms","Cnidarians"], correct:0, explain:"Octopus and squid are cephalopods, a highly intelligent group within the molluscs."},
{id:"c1-10", chapter:1, q:"Sea stars, sea urchins and sea cucumbers, many of which show radial symmetry and can regenerate lost body parts, belong to which group?", options:["Cnidarians","Echinoderms","Cephalopods","Crustaceans"], correct:1, explain:"Echinoderms include sea stars, sea urchins and sea cucumbers — many show radial symmetry and strong regenerative abilities."},
{id:"c1-11", chapter:1, q:"What is plankton primarily defined by?", options:["Their evolutionary relationships","Their lifestyle of drifting with ocean currents","Their large body size","Their ability to breathe air"], correct:1, explain:"Plankton are defined by lifestyle, not evolutionary relationship — they drift with currents rather than actively swimming against them."},
{id:"c1-12", chapter:1, q:"Which type of plankton photosynthesises and forms the base of many marine food webs?", options:["Zooplankton","Phytoplankton","Krill","Nekton"], correct:1, explain:"Phytoplankton are microscopic organisms that photosynthesise like plants, forming the foundation of most marine food webs and producing much of the world's oxygen."},
{id:"c1-13", chapter:1, q:"Which factor is described as one of the most powerful drivers of where marine species are found, affecting growth, reproduction and metabolism?", options:["Temperature","Colour of the water","Number of predators only","Tide timing"], correct:0, explain:"Temperature strongly influences species distribution because most organisms can only survive within a specific temperature range."},
{id:"c1-14", chapter:1, q:"The ocean zone that receives enough sunlight for photosynthesis is called the:", options:["Midnight zone","Twilight zone","Sunlit (photic) zone","Abyssal zone"], correct:2, explain:"The sunlit or photic zone extends from the surface to where enough light penetrates for phytoplankton to photosynthesise."},
{id:"c1-15", chapter:1, q:"What is 'upwelling'?", options:["The sinking of warm surface water","The upward movement of deep, nutrient-rich water toward the surface","The rising of sea levels due to climate change","A type of coral bleaching"], correct:1, explain:"Upwelling brings nutrient-rich deep water to the surface, boosting phytoplankton growth and making these regions highly productive fisheries."},
{id:"c1-16", chapter:1, q:"The pattern where species richness tends to increase toward the tropics and decrease toward the poles is called the:", options:["Latitudinal biodiversity gradient","Coral Triangle effect","Ecological niche pattern","Upwelling gradient"], correct:0, explain:"This well-documented pattern, the latitudinal biodiversity gradient, is linked to greater solar energy, longer evolutionary stability and higher productivity in tropical regions."},
{id:"c1-17", chapter:1, q:"An 'ecological niche' refers to:", options:["The exact GPS location of a species","The role a species plays in its ecosystem, including what it eats and how it interacts with others","A type of coral reef","The genetic makeup of a species"], correct:1, explain:"A niche describes a species' role within its ecosystem — what it eats, where it lives, and how it interacts with other organisms — allowing many species to coexist without excessive competition."},
{id:"c1-18", chapter:1, q:"Which of these marine regions is known as the 'Coral Triangle' and is considered the global centre of marine biodiversity?", options:["A region in the Indo-Pacific including Indonesia, Malaysia and the Philippines","The Mariana Trench","The Gulf of Mannar only","The Arctic Ocean"], correct:0, explain:"The Coral Triangle spans parts of Indonesia, Malaysia, the Philippines, Papua New Guinea, the Solomon Islands and Timor-Leste, and contains roughly 76% of known coral species."},
{id:"c1-19", chapter:1, q:"Which Indian marine region, located between India and Sri Lanka, is known for coral reefs, seagrass meadows and dugongs?", options:["Gulf of Mannar","Gulf of Kachchh","Andaman Sea","Bay of Bengal"], correct:0, explain:"The Gulf of Mannar, between India and Sri Lanka, supports coral reefs, seagrass meadows, mangroves, dugongs, sea cucumbers and reef fish."},
{id:"c1-20", chapter:1, q:"What is an 'endemic species'?", options:["A species found only in one geographic region and nowhere else","A species that has gone extinct","Any species living in the ocean","A species that migrates across oceans"], correct:0, explain:"Endemic species occur naturally in only one region, often because of long-term geographic isolation, which also makes them especially vulnerable to habitat loss."},
{id:"c1-21", chapter:1, q:"On the IUCN Red List, which category indicates the highest extinction risk (short of being extinct in the wild)?", options:["Near Threatened","Vulnerable","Critically Endangered","Least Concern"], correct:2, explain:"The IUCN Red List categories run from Least Concern up through Near Threatened, Vulnerable, Endangered, and Critically Endangered (the highest risk before Extinct in the Wild/Extinct)."},
{id:"c1-22", chapter:1, q:"What is 'bycatch'?", options:["The main species a fishery intends to catch","The accidental capture of non-target species during fishing","A method of tagging fish for research","A term for overfished species"], correct:1, explain:"Bycatch is the accidental capture of species that fishers did not intend to catch, such as sea turtles, dolphins and seabirds."},
{id:"c1-23", chapter:1, q:"Robotic underwater vehicles controlled remotely from a ship, used to explore depths too dangerous for human divers, are called:", options:["AUVs only","ROVs (Remotely Operated Vehicles)","Sonars","Submersible whales"], correct:1, explain:"ROVs are robotic vehicles controlled from the surface, carrying cameras and robotic arms to explore deep and dangerous ocean environments."},
{id:"c1-24", chapter:1, q:"Scientists can detect which species are present in an ecosystem by analysing genetic traces left in water samples, such as skin cells or mucus. This technique is called:", options:["Sonar mapping","Environmental DNA (eDNA)","Satellite telemetry","Taxonomy"], correct:1, explain:"eDNA analysis allows scientists to detect species from genetic material in water samples, without needing to directly observe or capture the organism."},

// ============================== CHAPTER 2 ==================================
{id:"c2-01", chapter:2, q:"What is the difference between a 'habitat' and an 'ecosystem'?", options:["They mean exactly the same thing","A habitat is where an organism lives; an ecosystem includes organisms, physical conditions and their interactions","An ecosystem is smaller than a habitat","A habitat only exists on land"], correct:1, explain:"A habitat is simply the place an organism lives (e.g. a mangrove root), while an ecosystem includes the organisms, the physical environment, and the interactions between them."},
{id:"c2-02", chapter:2, q:"Which of the following are 'abiotic factors' in a marine ecosystem?", options:["Fish and coral","Temperature, sunlight and currents","Bacteria and plankton","Predators and prey"], correct:1, explain:"Abiotic factors are non-living environmental conditions such as temperature, sunlight, currents and nutrients — as opposed to biotic (living) factors."},
{id:"c2-03", chapter:2, q:"Why are coral reefs often called the 'rainforests of the sea'?", options:["Because they contain actual rainforest trees","Because they occupy less than 1% of the seafloor yet support about 25% of ocean biodiversity","Because they only exist near tropical rainforests","Because they receive the most rainfall"], correct:1, explain:"Despite covering a tiny fraction of the seafloor, coral reefs' complex 3D structures support an extraordinary share of marine biodiversity."},
{id:"c2-04", chapter:2, q:"What is the symbiotic relationship between corals and zooxanthellae?", options:["The algae eat the coral's tissue","The algae photosynthesise and provide energy to the coral, while the coral provides shelter and nutrients","Zooxanthellae are parasites that harm corals","There is no real relationship between them"], correct:1, explain:"This mutualistic relationship is central to reef productivity — corals rely heavily on the energy their zooxanthellae produce through photosynthesis."},
{id:"c2-05", chapter:2, q:"What happens during 'coral bleaching'?", options:["Corals grow faster in cold water","Corals expel their zooxanthellae under heat stress, turning pale or white","Corals change colour to attract mates","Coral reefs are painted white by scientists for tracking"], correct:1, explain:"When ocean temperatures rise beyond normal ranges, corals may expel their symbiotic algae, causing bleaching; if stress continues, corals can die."},
{id:"c2-06", chapter:2, q:"Which specialised root structures help some mangrove species obtain oxygen in waterlogged, low-oxygen mud?", options:["Pneumatophores","Chromatophores","Photophores","Rhizomes"], correct:0, explain:"Pneumatophores are aerial roots that extend above the mud, helping mangroves access oxygen in oxygen-poor soils."},
{id:"c2-07", chapter:2, q:"Why are mangroves, seagrasses and salt marshes called 'blue carbon' ecosystems?", options:["Because they turn the ocean blue","Because they store large amounts of carbon in their biomass and sediments","Because they only exist in blue-coloured water","Because they absorb blue light specifically"], correct:1, explain:"These coastal ecosystems store carbon very efficiently in plant tissue and sediment, making them important for climate regulation."},
{id:"c2-08", chapter:2, q:"Seagrasses are different from seaweeds because:", options:["Seagrasses are true flowering plants with roots and vascular tissue, while seaweeds are algae","Seaweeds have flowers and seagrasses do not","Seagrasses only grow in the deep sea","There is no real difference"], correct:0, explain:"Seagrasses evolved from land plants and have roots, leaves, vascular tissue, flowers and seeds — unlike seaweeds, which are simpler algae."},
{id:"c2-09", chapter:2, q:"Dugongs are sometimes called 'sea cows' because they primarily feed on:", options:["Fish","Seagrass","Coral","Plankton"], correct:1, explain:"Dugongs graze on seagrass meadows, making healthy seagrass ecosystems essential for their survival."},
{id:"c2-10", chapter:2, q:"What is the 'pelagic zone'?", options:["The seafloor only","The water column away from coastlines and the seafloor","A type of coral reef","A polar-only region"], correct:1, explain:"The pelagic (open ocean) zone refers to the water column away from coasts and the seafloor, and forms the largest habitat on Earth."},
{id:"c2-11", chapter:2, q:"Organisms like tuna, sharks and squid that actively swim against ocean currents are called:", options:["Plankton","Nekton","Benthos","Detritivores"], correct:1, explain:"Nekton are organisms capable of powerful, directed swimming, unlike plankton which drift with currents."},
{id:"c2-12", chapter:2, q:"What is 'marine snow'?", options:["Frozen sea spray in polar regions","Sinking organic material such as dead plankton and waste that feeds deep-sea ecosystems","A type of white coral","Snowfall that lands directly on the ocean"], correct:1, explain:"Marine snow transports nutrients and energy from productive surface waters down into the deep sea, where food is otherwise scarce."},
{id:"c2-13", chapter:2, q:"How do hydrothermal vent ecosystems obtain energy, given there is no sunlight at those depths?", options:["Bacteria use chemosynthesis, converting chemicals like hydrogen sulfide into energy","They rely entirely on marine snow from the surface","They use bioluminescence to photosynthesise","They don't need energy at all"], correct:0, explain:"Vent bacteria use chemosynthesis instead of photosynthesis, forming the foundation of food webs that support tube worms, vent crabs and shrimp."},
{id:"c2-14", chapter:2, q:"What is a 'trophic level'?", options:["A depth measurement in the ocean","A feeding position within a food web (e.g. producer, primary consumer, apex predator)","A type of ocean current","A category of coral"], correct:1, explain:"Trophic levels describe an organism's position in a food chain — from producers like phytoplankton up to apex predators like sharks."},
{id:"c2-15", chapter:2, q:"Why do ecosystems typically contain many plankton but very few apex predators?", options:["Apex predators reproduce faster than plankton","Energy decreases at each step up the food web, so less energy is available to support organisms at higher trophic levels","Plankton are protected by law","Apex predators eat only plankton directly"], correct:1, explain:"Because organisms use much of their energy for movement, growth and reproduction, only a fraction of energy transfers to the next trophic level, limiting how many top predators an ecosystem can support."},
{id:"c2-16", chapter:2, q:"A 'keystone species' is one that:", options:["Is the most numerous species in an ecosystem","Has an ecological impact far greater than its abundance would suggest","Only lives in the deep sea","Cannot be removed from an ecosystem by natural causes"], correct:1, explain:"Sea otters are a classic keystone species example: by eating sea urchins, they prevent overgrazing of kelp forests — removing otters can trigger a trophic cascade."},
{id:"c2-17", chapter:2, q:"In a mutualistic relationship like that between cleaner wrasse and larger fish, what happens?", options:["Only one species benefits while the other is harmed","Both species benefit","Neither species is affected","One species is a parasite of the other"], correct:1, explain:"The cleaner wrasse gets food by removing parasites, while the larger fish benefits from reduced parasite loads — both species benefit."},
{id:"c2-18", chapter:2, q:"Which of these is an example of commensalism, where one species benefits and the other is largely unaffected?", options:["Corals and zooxanthellae","Remoras attaching to sharks for transport and food scraps","Sea otters and sea urchins","Cleaner wrasse and larger fish"], correct:1, explain:"Remoras gain transportation, protection and food scraps from sharks, while the shark is usually not significantly affected either way."},
{id:"c2-19", chapter:2, q:"What are 'ecosystem services'?", options:["Fees charged for visiting marine parks","Benefits that humans obtain from ecosystems, such as food, climate regulation and coastal protection","A list of endangered species","Government regulations on fishing"], correct:1, explain:"Ecosystem services include provisioning (food, medicine), regulating (climate, coastal protection), supporting (nutrient cycling) and cultural services."},
{id:"c2-20", chapter:2, q:"Why do phytoplankton matter so much for the whole planet, not just the ocean?", options:["They are the tastiest food for whales","They contribute significantly to global oxygen production through photosynthesis","They control ocean tides","They prevent all storms"], correct:1, explain:"As microscopic photosynthesisers, phytoplankton are a major source of the planet's oxygen and form the base of most marine food webs."},
{id:"c2-21", chapter:2, q:"The Great Barrier Reef, the world's largest coral reef system, is located off the coast of:", options:["India","Australia","Mexico","South Africa"], correct:1, explain:"The Great Barrier Reef stretches over 2,300 kilometres off the coast of Australia and supports thousands of reef species."},
{id:"c2-22", chapter:2, q:"Why is the Sundarbans significant among the world's mangrove ecosystems?", options:["It is the smallest mangrove forest in the world","It is the world's largest mangrove forest system, shared by India and Bangladesh","It contains no wildlife","It is located in the Pacific Ocean"], correct:1, explain:"The Sundarbans, spanning more than 10,000 sq km across India and Bangladesh, is the largest mangrove forest system on Earth."},

// ============================== CHAPTER 3 ==================================
{id:"c3-01", chapter:3, q:"An organism that can be divided into two mirror-image halves along a single line (like most fish and sharks) shows which body plan?", options:["Radial symmetry","Bilateral symmetry","Asymmetry","Hydrostatic symmetry"], correct:1, explain:"Bilateral symmetry, seen in fish, sharks and turtles, often supports efficient directional movement for hunting or escaping predators."},
{id:"c3-02", chapter:3, q:"Jellyfish and sea anemones, which can be divided into similar sections around a central point, show which body plan?", options:["Bilateral symmetry","Radial symmetry","Endoskeleton structure","Convergent symmetry"], correct:1, explain:"Radial symmetry allows organisms like sea anemones to respond to prey or threats coming from any direction."},
{id:"c3-03", chapter:3, q:"Crabs, lobsters and shrimp have external skeletons that must be periodically shed as they grow. This is called:", options:["Metamorphosis","Moulting","Regeneration","Camouflage"], correct:1, explain:"Because exoskeletons don't grow continuously, crustaceans must moult (shed their shell) periodically to grow larger."},
{id:"c3-04", chapter:3, q:"Sharks and dolphins have similar streamlined, torpedo-shaped bodies even though one is a fish and the other is a mammal. This is an example of:", options:["Radial symmetry","Convergent evolution","Bioluminescence","Symbiosis"], correct:1, explain:"Convergent evolution occurs when unrelated species independently evolve similar traits because they face similar environmental challenges — here, moving efficiently through water."},
{id:"c3-05", chapter:3, q:"Why is breathing underwater more difficult than breathing air?", options:["Water contains no oxygen at all","Water holds much less oxygen than air and is denser, requiring more effort to extract oxygen","Fish don't actually need oxygen","Underwater breathing is easier, not harder"], correct:1, explain:"Water contains far less dissolved oxygen than air, and is heavier to move across respiratory surfaces, making gills and specialised breathing adaptations necessary."},
{id:"c3-06", chapter:3, q:"What is the main function of gills in fish?", options:["To help the fish swim faster","To extract oxygen from water as it flows across them","To store food for digestion","To produce bioluminescent light"], correct:1, explain:"Gills are respiratory organs with thin, blood-vessel-rich surfaces where oxygen from water diffuses into the bloodstream."},
{id:"c3-07", chapter:3, q:"Why must whales, dolphins and seals regularly return to the surface even though they live in water?", options:["They are actually fish and need to feed at the surface","They are mammals with lungs and must breathe air","They surface only to sleep","They need sunlight for photosynthesis"], correct:1, explain:"Marine mammals evolved from land-dwelling ancestors and retained lungs, so despite living in water, they must surface to breathe air."},
{id:"c3-08", chapter:3, q:"A whale's blowhole is best described as:", options:["A gill used to extract oxygen from water","The whale's nostril, located on top of its head","A sensory organ for detecting prey","An organ used only for making sounds"], correct:1, explain:"The blowhole is a modified nostril that lets whales breathe quickly at the surface without lifting their whole head out of the water."},
{id:"c3-09", chapter:3, q:"Filter feeders like baleen whales and whale sharks obtain food by:", options:["Actively hunting large prey with sharp teeth","Straining tiny organisms such as plankton or krill from large volumes of water","Only scavenging dead animals","Photosynthesising like plants"], correct:1, explain:"Filter feeders use specialised structures (like baleen plates) to trap small organisms while letting water pass through — useful where plankton occur in huge numbers."},
{id:"c3-10", chapter:3, q:"Parrotfish are important on coral reefs mainly because they:", options:["Hunt sharks","Graze algae off coral surfaces, helping prevent reefs from being overgrown","Produce bioluminescent light","Filter feed on plankton only"], correct:1, explain:"As grazers, parrotfish help control algal growth on reefs, which helps maintain the balance needed for corals to thrive."},
{id:"c3-11", chapter:3, q:"Sea cucumbers, which extract organic material directly from ocean sediments, are examples of:", options:["Filter feeders","Deposit feeders","Apex predators","Scavengers only"], correct:1, explain:"Deposit feeders like sea cucumbers consume sediment, digesting the organic particles and microorganisms within it."},
{id:"c3-12", chapter:3, q:"Squid and octopuses move rapidly through water by:", options:["Using fins like fish","Jet propulsion — drawing water into their body and expelling it through a funnel-like structure","Flying above the water","Rolling along the seafloor"], correct:1, explain:"Jet propulsion allows squid and octopuses fast bursts of movement for escape or hunting, though it uses more energy than steady swimming."},
{id:"c3-13", chapter:3, q:"What is the main function of a swim bladder in many bony fish?", options:["To help the fish see in the dark","To regulate buoyancy so the fish can stay at a chosen depth without constantly swimming","To produce electricity","To store extra oxygen for deep dives only"], correct:1, explain:"By adjusting the gas volume in their swim bladder, fish can rise, sink or remain suspended at a particular depth without expending constant energy."},
{id:"c3-14", chapter:3, q:"Since sharks lack swim bladders, how do many species maintain buoyancy instead?", options:["They cannot control buoyancy at all and constantly sink","Using large, oil-rich livers and lift generated while swimming","By breathing air like whales","By floating on the surface only"], correct:1, explain:"Shark livers contain oils that are less dense than water, helping improve buoyancy, along with lift generated as they swim."},
{id:"c3-15", chapter:3, q:"The sensory system in fish that detects vibrations and water movement along the sides of their body is called the:", options:["Lateral line","Ampullae of Lorenzini","Melon organ","Operculum"], correct:0, explain:"The lateral line helps fish detect nearby movement, avoid collisions, and coordinate schooling, even in murky or dark water."},
{id:"c3-16", chapter:3, q:"Dolphins locate prey in murky water by producing clicking sounds and interpreting the returning echoes. This ability is called:", options:["Electroreception","Echolocation","Bioluminescence","Chemoreception"], correct:1, explain:"Echolocation lets dolphins and toothed whales determine an object's distance, size, shape and movement by analysing returning sound echoes."},
{id:"c3-17", chapter:3, q:"Sharks and rays can detect the weak electrical fields produced by other animals' muscles and nerves using organs called:", options:["Ampullae of Lorenzini","Lateral lines","Blowholes","Chromatophores"], correct:0, explain:"Ampullae of Lorenzini are jelly-filled pores around a shark's head that detect tiny electrical signals, helping locate hidden prey."},
{id:"c3-18", chapter:3, q:"Reproduction where eggs and sperm are released into the surrounding water, and fertilisation happens outside the body, is called:", options:["Internal fertilisation","External fertilisation","Asexual reproduction only","Metamorphosis"], correct:1, explain:"External fertilisation is common in many fish, corals and sea urchins, and typically involves producing enormous numbers of eggs since many will not survive."},
{id:"c3-19", chapter:3, q:"What is 'metamorphosis' in marine organisms?", options:["A change in water temperature","A major transformation in body form as an organism develops from larva to adult","The process of moulting an exoskeleton","A type of camouflage"], correct:1, explain:"Many marine organisms undergo metamorphosis, where larvae look completely different from adults, reducing competition between life stages."},
{id:"c3-20", chapter:3, q:"In seahorses, which is true about reproduction?", options:["Females carry the developing embryos in a pouch","Males carry the developing embryos in a specialised brood pouch","Seahorses do not reproduce sexually","Seahorses lay eggs directly on the seafloor with no parental care"], correct:1, explain:"Male seahorses carry developing embryos in a brood pouch and release fully formed young — an unusual reproductive strategy among vertebrates."},

// ============================== CHAPTER 4 ==================================
{id:"c4-01", chapter:4, q:"In biology, what is the precise meaning of 'adaptation'?", options:["Something an animal learns during its own lifetime","An inherited trait, shaped over many generations by natural selection, that improves survival and reproduction","Any change an organism makes to its daily routine","A behaviour copied from another species"], correct:1, explain:"Unlike the everyday use of the word, a biological adaptation accumulates over generations through natural selection — it is not learned or chosen within one lifetime."},
{id:"c4-02", chapter:4, q:"Which three ingredients does natural selection require to work, according to the chapter?", options:["Variation, heredity, and differential survival/reproduction","Speed, size, and colour","Camouflage, migration, and bioluminescence","Warm water, sunlight, and oxygen"], correct:0, explain:"Natural selection requires variation among individuals, the ability to pass traits to offspring (heredity), and traits that affect survival and reproductive success."},
{id:"c4-03", chapter:4, q:"Giant tube worms living near hydrothermal vents survive without a mouth or digestive system because:", options:["They absorb sunlight directly","They house chemosynthetic bacteria in an organ called a trophosome, which converts vent chemicals into energy","They eat through their skin","They don't need any energy source"], correct:1, explain:"The bacteria inside the trophosome use chemosynthesis to produce nutrients that support the tube worm, an extreme adaptation to a sunless environment."},
{id:"c4-04", chapter:4, q:"Camouflage where an animal's colour and pattern closely resemble its surroundings is called:", options:["Mimicry","Background matching","Bioluminescence","Echolocation"], correct:1, explain:"Background matching is one of the two broad forms of camouflage, alongside mimicry (imitating another species)."},
{id:"c4-05", chapter:4, q:"The mimic octopus is famous for:", options:["Producing the loudest sound in the ocean","Impersonating several different dangerous species, such as lionfish or sea snakes, by changing its shape and movement","Being the only bioluminescent octopus","Having the largest eyes of any animal"], correct:1, explain:"The mimic octopus can switch between multiple disguises depending on which predator is nearby, rather than relying on one fixed appearance."},
{id:"c4-06", chapter:4, q:"Cephalopods like cuttlefish change colour almost instantly using pigment-filled skin cells called:", options:["Chromatophores","Ampullae of Lorenzini","Pneumatophores","Photophores"], correct:0, explain:"Chromatophores are controlled directly by the nervous system, letting cephalopods shift colour and pattern within a fraction of a second."},
{id:"c4-07", chapter:4, q:"Roughly what percentage of animals living between 200 and 1,000 metres depth are estimated to produce their own light?", options:["About 5%","About 30%","About 80%","Nearly 100%"], correct:2, explain:"According to NOAA Ocean Exploration, roughly 80% of animals in this deep mid-water zone are bioluminescent, making it possibly the most common form of communication on the planet."},
{id:"c4-08", chapter:4, q:"Bioluminescence is produced through a chemical reaction between:", options:["Water and salt","Luciferin, the enzyme luciferase, and oxygen","Carbon dioxide and sunlight","Melanin and heat"], correct:1, explain:"This reaction releases light with almost none of the energy lost as heat, unlike an ordinary light bulb."},
{id:"c4-09", chapter:4, q:"When threatened, a sea cucumber may eject some of its own internal organs. This defensive strategy is called:", options:["Metamorphosis","Evisceration","Bioluminescence","Chemosynthesis"], correct:1, explain:"Sea cucumbers can eject organs as a decoy or to release sticky toxic threads, then regrow the lost tissue within weeks."},
{id:"c4-10", chapter:4, q:"A starfish deliberately detaching its own arm to escape a predator is called:", options:["Camouflage","Autotomy","Migration","Countershading"], correct:1, explain:"Autotomy is a voluntary, deliberate escape strategy, triggered by a specific neurohormone, rather than an accidental loss."},
{id:"c4-11", chapter:4, q:"Why is sound often a more effective way to communicate underwater than sight?", options:["Sound cannot travel through water at all","Sound travels roughly four times faster in water than in air and can carry across huge distances","Light travels faster underwater than sound","Underwater animals cannot hear sound"], correct:1, explain:"Because sound travels efficiently and quickly through water, many marine mammals rely on it as their primary way to communicate and navigate."},
{id:"c4-12", chapter:4, q:"Which whale group (including humpback and blue whales) produces low-frequency pulses, moans and whoops that travel very long distances?", options:["Odontocetes (toothed whales)","Mysticetes (baleen whales)","Pinnipeds","Cephalopods"], correct:1, explain:"Mysticetes, or baleen whales, produce low-frequency sounds, while odontocetes (toothed whales like orcas and dolphins) produce higher-frequency clicks and whistles."},
{id:"c4-13", chapter:4, q:"What is the key difference between 'shoaling' and 'schooling' in fish?", options:["They mean exactly the same thing","Shoaling is any loose social gathering; schooling is a tightly coordinated, synchronised group of the same species","Schooling only happens in freshwater","Shoaling only happens among predators"], correct:1, explain:"True schooling — tight synchrony in speed and direction — is seen in only about a quarter of fish species, while shoaling (looser social gathering) is more common."},
{id:"c4-14", chapter:4, q:"Which of these is NOT a commonly cited benefit of schooling behaviour?", options:["Confusing predators (confusion effect)","Reducing individual predation risk (dilution effect)","Improving foraging efficiency","Guaranteeing that no individual is ever eaten"], correct:3, explain:"Schooling reduces risk through confusion and dilution effects and can improve feeding, but it does not guarantee complete safety for every individual."},
{id:"c4-15", chapter:4, q:"Migration in marine animals is usually driven by the need to:", options:["Avoid all contact with other members of their species","Find food, reach breeding grounds, or avoid unfavourable conditions","Stay in exactly the same spot their whole lives","Change their body colour permanently"], correct:1, explain:"Whether it's whales, turtles or tuna, migration is generally linked to feeding, breeding, or escaping conditions like extreme cold."},
{id:"c4-16", chapter:4, q:"The sea turtle 'lost years' refers to:", options:["The years turtles spend in captivity","The poorly understood period between when hatchlings leave the nesting beach and when they reappear as juveniles at feeding grounds","The years before a turtle's egg hatches","A period when turtles stop growing"], correct:1, explain:"Satellite tagging research helped reveal that young turtles actively use areas like the Sargasso Sea during this period, rather than simply drifting passively."},
{id:"c4-17", chapter:4, q:"The sense that allows sea turtles to detect Earth's magnetic field and helps guide their long migrations is called:", options:["Echolocation","Magnetoreception","Electroreception","Chemoreception"], correct:1, explain:"Magnetoreception lets turtles sense the unique magnetic 'signature' of coastal locations, helping them navigate back to their natal beach even after journeys of thousands of kilometres."},
{id:"c4-18", chapter:4, q:"What is 'natal homing' in sea turtles?", options:["The tendency of adult turtles to return to nest on the same beach where they themselves hatched","A turtle's ability to build a nest anywhere","A turtle's first migration as a hatchling","A method scientists use to tag turtles"], correct:0, explain:"Natal homing means adult turtles often return to their birth beach to nest, sometimes after journeys spanning thousands of kilometres and many years."},
{id:"c4-19", chapter:4, q:"Which structural feature helps reduce drag and allows fast swimmers like tuna and dolphins to move efficiently through water?", options:["A streamlined, tapered body shape","A hard exoskeleton","Radial symmetry","A hydrostatic skeleton"], correct:0, explain:"Streamlined bodies reduce resistance (drag) in water, which is much denser than air, allowing efficient, energy-saving movement."},
{id:"c4-20", chapter:4, q:"Counter-illumination, a bioluminescent camouflage strategy used by some marine animals, works by:", options:["Making the animal glow brightly to scare predators away","Matching faint light from above on the underside of the body, making the animal harder to see in silhouette from below","Producing loud sounds instead of light","Turning the animal's entire body transparent"], correct:1, explain:"Counter-illumination helps an animal blend into the faint light coming from the surface above, making it less visible to predators looking upward from below."},

// ============================== CHAPTER 5 ==================================
{id:"c5-01", chapter:5, q:"Why do oceans play an important role in slowing down global warming on land?", options:["Oceans reflect all sunlight back into space","Oceans absorb large amounts of heat and carbon dioxide from the atmosphere","Oceans have stopped absorbing any heat","Oceans are unaffected by the atmosphere"], correct:1, explain:"By absorbing excess heat and CO2, oceans reduce warming on land to some extent — but this creates major changes within marine ecosystems themselves."},
{id:"c5-02", chapter:5, q:"What is 'ocean acidification'?", options:["Oceans becoming more acidic as they absorb carbon dioxide from the atmosphere","A type of pollution caused only by oil spills","The process of seawater freezing","A method used to clean plastic from the ocean"], correct:0, explain:"As CO2 dissolves into seawater, oceans become slightly more acidic, which can affect organisms that build shells or skeletons from calcium carbonate, like corals and oysters."},
{id:"c5-03", chapter:5, q:"Which of these is NOT a major cause of rising sea levels?", options:["Thermal expansion of warming seawater","Melting glaciers and ice sheets","Coral bleaching","Both A and B are causes, so C is the odd one out"], correct:3, explain:"Sea-level rise is driven by seawater expanding as it warms and by melting ice adding more water to the ocean — coral bleaching is a separate impact of warming, not a direct cause of sea-level rise."},
{id:"c5-04", chapter:5, q:"Tiny plastic fragments, formed when larger plastic breaks down in the ocean, are called:", options:["Ghost gear","Microplastics","Marine snow","Ballast water"], correct:1, explain:"Microplastics have now been detected across nearly all major ocean ecosystems, including deep oceans and polar regions."},
{id:"c5-05", chapter:5, q:"Lost or abandoned fishing gear that continues trapping fish, turtles and other marine animals is known as:", options:["Ghost gear","Bycatch","Ballast water","Marine debris only"], correct:0, explain:"Ghost gear is considered one of the major forms of marine debris, as it can keep catching animals long after being discarded."},
{id:"c5-06", chapter:5, q:"What is the difference between 'habitat loss' and 'habitat degradation'?", options:["They mean the same thing","Habitat loss is complete removal of a habitat; degradation means the habitat remains but functions less effectively","Habitat degradation only happens on land","Habitat loss cannot be caused by humans"], correct:1, explain:"For example, clearing a mangrove forest entirely is habitat loss, while pollution making a mangrove less suitable for wildlife (without removing it) is degradation."},
{id:"c5-07", chapter:5, q:"What does 'habitat fragmentation' mean?", options:["Habitats becoming larger and more connected","Breaking habitats into smaller, disconnected pieces","A habitat disappearing completely","Habitats being restored to full health"], correct:1, explain:"Even when some habitat remains, fragmentation can reduce breeding opportunities, limit movement and increase vulnerability to disturbance."},
{id:"c5-08", chapter:5, q:"Overfishing occurs when:", options:["Fish are harvested slower than they can reproduce","Fish are removed from a population faster than they can naturally replace themselves","No fish are caught at all","Fisheries use only sustainable methods"], correct:1, explain:"Like a bank account being drawn down faster than it's refilled, overfishing gradually depletes a population, sometimes without being noticed until it's severe."},
{id:"c5-09", chapter:5, q:"Why are sharks and rays especially vulnerable to overfishing compared to many bony fish?", options:["They reproduce very quickly and in huge numbers","They generally grow slowly, mature late, and produce relatively few offspring","They live only in freshwater","They are immune to fishing gear"], correct:1, explain:"Slow growth and low reproduction rates mean shark and ray populations take much longer to recover once they decline."},
{id:"c5-10", chapter:5, q:"Turtle Excluder Devices (TEDs) are used in fishing nets to:", options:["Catch more turtles for research","Allow sea turtles to escape trawl nets while retaining the target catch","Attract more fish into the net","Track fish using satellites"], correct:1, explain:"TEDs are considered one of the most successful technologies for reducing sea turtle bycatch in fisheries like shrimp trawling."},
{id:"c5-11", chapter:5, q:"What does 'IUU fishing' stand for?", options:["Illegal, Unreported and Unregulated fishing","International Union for Underwater fishing","Illegal Use of Underwater equipment","Individual, Unlicensed and Unsafe fishing"], correct:0, explain:"IUU fishing undermines sustainable fisheries management and, according to the FAO, costs the global economy billions of dollars annually."},
{id:"c5-12", chapter:5, q:"An 'invasive species' is best defined as:", options:["Any species that lives in the ocean","A species introduced outside its natural range that spreads rapidly and causes ecological, economic or social harm","A species that has gone extinct","A species that only lives in polar regions"], correct:1, explain:"Not every introduced species becomes invasive — but those that thrive without natural predators can alter food webs and damage habitats, like the lionfish invasion in the Atlantic and Caribbean."},
{id:"c5-13", chapter:5, q:"Ballast water, taken on by large ships for stability, is a major pathway for invasive species because:", options:["It kills all marine organisms instantly","It can carry plankton, larvae and small organisms that get released far from their native range","It is always sterilised before release","It only carries seaweed"], correct:1, explain:"Ships take in seawater (and its organisms) in one region and may release it thousands of kilometres away, introducing species to new ecosystems."},
{id:"c5-14", chapter:5, q:"What is the difference between 'extinction' and 'extirpation'?", options:["They are identical terms","Extinction means a species disappears everywhere; extirpation means it disappears from one area but survives elsewhere","Extirpation is always caused by humans, extinction never is","Extinction can be reversed, extirpation cannot"], correct:1, explain:"Understanding this difference helps conservationists judge where recovery efforts might still succeed — an extirpated species could potentially be reintroduced from elsewhere."},
{id:"c5-15", chapter:5, q:"What is 'functional extinction'?", options:["When a species' population declines so much it can no longer perform its ecological role, even though a few individuals remain","The complete disappearance of a species from Earth","A species being renamed by scientists","When a species is moved to a zoo"], correct:0, explain:"For example, a predator may still exist in small numbers but no longer regulate prey populations effectively — this can damage ecosystem health even before full extinction."},
{id:"c5-16", chapter:5, q:"India's dugong populations are found in regions including the Gulf of Mannar, Palk Bay, and:", options:["The Mariana Trench","The Andaman and Nicobar Islands","The Arctic Ocean","The Sargasso Sea"], correct:1, explain:"India's dugong populations depend on seagrass habitats in these regions, and are vulnerable to habitat degradation and accidental capture in fishing gear."},
{id:"c5-17", chapter:5, q:"Nearly what percentage of the world's population lives within 100 kilometres of a coastline?", options:["About 5%","About 40%","About 90%","100%"], correct:1, explain:"This concentration of people near coasts means decisions made along coastlines can affect both human communities and marine ecosystems on a massive scale."},

// ============================== CHAPTER 6 ==================================
{id:"c6-01", chapter:6, q:"What does 'Traditional Ecological Knowledge' (TEK) refer to?", options:["Knowledge only found in modern science textbooks","Environmental understanding developed by communities over generations of observing tides, seasons, and local ecosystems","A GPS-based mapping system","A rule created by international law"], correct:1, explain:"Many coastal and Indigenous communities developed detailed ecological knowledge long before modern instruments existed, and this knowledge increasingly informs conservation efforts."},
{id:"c6-02", chapter:6, q:"The Haenyeo of Jeju Island, South Korea, are known for:", options:["Building large fishing trawlers","Diving without scuba equipment to harvest shellfish and seaweed using breath-holding skills","Farming seaweed only using drones","Leading international ocean treaties"], correct:1, explain:"UNESCO has recognised Haenyeo culture as an Intangible Cultural Heritage of Humanity, showing how humans can sustainably harvest marine resources through traditional skill."},
{id:"c6-03", chapter:6, q:"What is a 'wild capture fishery'?", options:["A fishery where organisms are farmed in tanks","Harvesting fish and other organisms directly from natural ecosystems rather than farming them","A fishery that only operates illegally","A type of aquarium"], correct:1, explain:"Most marine fisheries are wild capture fisheries, harvesting organisms directly from oceans, rivers or estuaries."},
{id:"c6-04", chapter:6, q:"Which fishing method involves dragging large nets through the water or across the seafloor?", options:["Longline fishing","Trawling","Purse seining only","Hand-lining"], correct:1, explain:"Trawling is one of several fishing methods, each with different environmental impacts and levels of bycatch."},
{id:"c6-05", chapter:6, q:"What is a Marine Protected Area (MPA)?", options:["A region where all human activity is completely banned forever","An ocean region where activities like fishing are restricted or carefully managed to protect ecosystems and biodiversity","A private beach resort","An area only used for shipping"], correct:1, explain:"MPAs may help fish populations recover by protecting important habitats such as coral reefs, mangroves and seagrass beds, and can benefit nearby fisheries too."},
{id:"c6-06", chapter:6, q:"What does 'ecosystem-based fisheries management' consider, compared to traditional single-species management?", options:["Only the price of fish in the market","Habitats, food webs, biodiversity and environmental change together, not just one species alone","Only the size of fishing boats","Nothing related to ecosystems"], correct:1, explain:"This more holistic approach is becoming increasingly important as climate change alters marine ecosystems in complex ways."},
{id:"c6-07", chapter:6, q:"The United Nations Convention on the Law of the Sea (UNCLOS), often called the 'Constitution of the Oceans', was adopted in:", options:["1945","1982","2001","2023"], correct:1, explain:"UNCLOS, adopted in 1982, established frameworks including Exclusive Economic Zones (EEZs) that still guide ocean governance today."},
{id:"c6-08", chapter:6, q:"An Exclusive Economic Zone (EEZ) generally extends how far from a coastal country's coastline?", options:["12 nautical miles","50 nautical miles","200 nautical miles","1,000 nautical miles"], correct:2, explain:"Under UNCLOS, coastal countries generally have special rights to marine resources within 200 nautical miles of their coastline — India's EEZ covers more than 2 million square kilometres."},
{id:"c6-09", chapter:6, q:"What are the 'High Seas'?", options:["Areas within a country's territorial waters","Waters lying outside any country's Exclusive Economic Zone, accounting for nearly two-thirds of the ocean","Only the surface layer of the ocean","A term for polar oceans only"], correct:1, explain:"Because no single country manages the High Seas, protecting biodiversity there has historically been challenging — leading to newer agreements like the 2023 BBNJ (High Seas) Treaty."},
{id:"c6-10", chapter:6, q:"The Convention on Biological Diversity (CBD), adopted in 1992, aims to:", options:["Only regulate international shipping routes","Conserve biodiversity, promote sustainable use of biological resources, and ensure fair sharing of benefits from genetic resources","Ban all fishing worldwide","Only protect forest ecosystems"], correct:1, explain:"Although often associated with forests, the CBD also plays an important role in marine conservation and biodiversity targets."},
{id:"c6-11", chapter:6, q:"What is 'citizen science'?", options:["Science that can only be done by professional scientists","Public participation in scientific research, such as reporting whale sightings or monitoring coral bleaching","A government policy about fishing licences","A type of underwater robot"], correct:1, explain:"Citizen science allows members of the public to contribute valuable observations that would be difficult for scientists to collect alone across huge areas."},
{id:"c6-12", chapter:6, q:"Robotic vehicles like ROVs and AUVs are useful in ocean science mainly because they:", options:["Can travel through deep, high-pressure ocean environments that are dangerous or impossible for human divers","Can only operate in shallow swimming pools","Replace the need for any scientific research","Cannot carry cameras or sensors"], correct:0, explain:"These vehicles let scientists study extreme environments like hydrothermal vents and deep trenches without risking human divers."},
{id:"c6-13", chapter:6, q:"Underwater microphones used to record whale calls and other ocean sounds are called:", options:["Sonars","Hydrophones","Chromatophores","Photophores"], correct:1, explain:"This field of study is called bioacoustics, and it helps scientists study whale migration, communication and behaviour without needing to see the animals directly."},
{id:"c6-14", chapter:6, q:"Why did humpback whale populations recover so strongly after being reduced by more than 90% during the industrial whaling era?", options:["Whales adapted to survive without any protection","International agreements restricted commercial whaling and reduced threats, allowing populations to recover over decades","Humpback whales moved permanently to freshwater rivers","No conservation action was actually needed"], correct:1, explain:"The humpback whale's recovery is often cited as one of the world's most successful marine conservation stories, showing that reducing threats allows species to rebound."},
{id:"c6-15", chapter:6, q:"How did community involvement help conserve whale sharks along India's Gujarat coast?", options:["Fishers were fined heavily with no other support","Awareness campaigns and compensation programmes helped fishers move from hunting whale sharks to protecting them","The government banned all fishing in Gujarat entirely","Whale sharks were relocated to zoos"], correct:1, explain:"Legal protection under India's Wildlife (Protection) Act, combined with community awareness and support, turned former hunters into some of the whale shark's strongest protectors."},
{id:"c6-16", chapter:6, q:"The Gahirmatha and Rushikulya coasts in Odisha are globally significant because they host mass nesting events, called arribadas, of which species?", options:["Humpback whales","Olive Ridley sea turtles","Whale sharks","Dugongs"], correct:1, explain:"Hundreds of thousands of Olive Ridley turtles come ashore over just a few nights during an arribada, making Odisha one of the most important sea turtle conservation regions in the world."},
{id:"c6-17", chapter:6, q:"The UN declared 2021-2030 as the:", options:["Decade of Ocean Science for Sustainable Development","Decade of Deep-Sea Mining","International Year of the Whale","Decade of Coral Restoration Only"], correct:0, explain:"Known as 'the Ocean Decade', this initiative aims to bring together scientists, governments, communities and organisations to support sustainable ocean management."},
{id:"c6-18", chapter:6, q:"Which of these is an example of a genuine, evidence-based way a student can contribute to ocean conservation, according to the learning material?", options:["Only professional marine biologists can help oceans","Reducing plastic waste, supporting sustainable seafood choices, and participating in citizen science projects","Ignoring ocean issues until adulthood","Avoiding all learning about marine ecosystems"], correct:1, explain:"The material emphasises that protecting oceans is a shared responsibility, and that everyday actions and citizen participation genuinely matter alongside scientific and government efforts."},

];

// Sanity check helper (used only during development, harmless in production)
if (typeof window !== "undefined") {
  window.QUESTION_BANK = QUESTION_BANK;
}
